#!/usr/bin/env bash
set -euo pipefail

# DLR Bootstrap — provisions a fresh Ubuntu 24.04 server into a running DLR instance.
#
# Usage:
#   sudo ./scripts/bootstrap.sh <domain>
#
# Example:
#   sudo ./scripts/bootstrap.sh app.dlr.com
#
# Prerequisites:
#   - Fresh Ubuntu 24.04 server with a public IP
#   - DNS A record for <domain> pointing to this server's IP
#   - Run as root or with sudo

DOMAIN="${1:-}"
if [ -z "$DOMAIN" ]; then
  echo "Usage: sudo ./scripts/bootstrap.sh <domain>"
  echo "Example: sudo ./scripts/bootstrap.sh app.dlr.com"
  exit 1
fi

APP_DIR="/opt/dlr"
APP_USER="dlr"

echo "=== DLR Bootstrap ==="
echo "Domain: $DOMAIN"
echo ""

# ── Collect secrets interactively ────────────────────────────────────────────

read -rp "Telnyx API key: " TELNYX_API_KEY
read -rp "Telnyx public key (base64 Ed25519): " TELNYX_PUBLIC_KEY
read -rp "Admin email for dashboard login: " ADMIN_EMAIL
read -rsp "Admin password: " ADMIN_PASSWORD
echo ""
read -rp "Telnyx phone number (E.164, e.g. +18015155345): " SEED_PHONE

# Auto-generate secrets
PG_PASSWORD=$(openssl rand -hex 16)
NEXTAUTH_SECRET=$(openssl rand -hex 32)

echo ""
echo "=== Installing system packages ==="

# ── System packages ──────────────────────────────────────────────────────────

apt-get update -qq
apt-get install -y -qq curl gnupg2 git

# ── Node.js 20 ───────────────────────────────────────────────────────────────

if ! command -v node &>/dev/null; then
  echo "Installing Node.js 20..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y -qq nodejs
fi
echo "Node: $(node -v)"

# ── Postgres ─────────────────────────────────────────────────────────────────

if ! command -v psql &>/dev/null; then
  echo "Installing PostgreSQL..."
  apt-get install -y -qq postgresql postgresql-contrib
fi
systemctl enable postgresql
systemctl start postgresql

echo "Creating DLR database and user..."
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='dlr'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE ROLE dlr WITH LOGIN PASSWORD '$PG_PASSWORD';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='dlr'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE DATABASE dlr OWNER dlr;"
echo "Postgres: ready"

# ── Redis ────────────────────────────────────────────────────────────────────

if ! command -v redis-server &>/dev/null; then
  echo "Installing Redis..."
  apt-get install -y -qq redis-server
fi
systemctl enable redis-server
systemctl start redis-server
echo "Redis: ready"

# ── Caddy ────────────────────────────────────────────────────────────────────

if ! command -v caddy &>/dev/null; then
  echo "Installing Caddy..."
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy
fi
echo "Caddy: ready"

# ── pm2 ──────────────────────────────────────────────────────────────────────

if ! command -v pm2 &>/dev/null; then
  echo "Installing pm2..."
  npm install -g pm2
fi
echo "pm2: ready"

# ── DLR app user ─────────────────────────────────────────────────────────────

if ! id "$APP_USER" &>/dev/null; then
  useradd --system --home "$APP_DIR" --shell /bin/bash "$APP_USER"
fi

# ── Deploy DLR code ──────────────────────────────────────────────────────────

echo ""
echo "=== Deploying DLR ==="

if [ -d "$APP_DIR/.git" ]; then
  echo "Updating existing deployment..."
  cd "$APP_DIR"
  sudo -u "$APP_USER" git pull --ff-only
else
  echo "Copying project to $APP_DIR..."
  mkdir -p "$APP_DIR"

  # Copy from wherever the script is being run
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  cp -r "$SCRIPT_DIR"/. "$APP_DIR"/
  rm -rf "$APP_DIR"/node_modules "$APP_DIR"/.next

  chown -R "$APP_USER":"$APP_USER" "$APP_DIR"
fi

cd "$APP_DIR"

# ── Environment file ─────────────────────────────────────────────────────────

echo "Writing .env..."
cat > "$APP_DIR/.env" <<ENVFILE
# DLR production environment — generated by bootstrap.sh
DATABASE_URL=postgresql://dlr:${PG_PASSWORD}@localhost:5432/dlr
REDIS_URL=redis://localhost:6379
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=https://${DOMAIN}
TELNYX_API_KEY=${TELNYX_API_KEY}
TELNYX_PUBLIC_KEY=${TELNYX_PUBLIC_KEY}
NODE_ENV=production
ENVFILE

chown "$APP_USER":"$APP_USER" "$APP_DIR/.env"
chmod 600 "$APP_DIR/.env"

# ── Install, build, migrate, seed ────────────────────────────────────────────

echo ""
echo "=== Building DLR ==="

sudo -u "$APP_USER" bash -c "cd $APP_DIR && npm ci"
sudo -u "$APP_USER" bash -c "cd $APP_DIR && npm run build"

echo "Running database migration..."
sudo -u "$APP_USER" bash -c "cd $APP_DIR && npx drizzle-kit migrate"

echo "Seeding database..."
sudo -u "$APP_USER" bash -c "cd $APP_DIR && \
  SEED_ADMIN_EMAIL='$ADMIN_EMAIL' \
  SEED_ADMIN_PASSWORD='$ADMIN_PASSWORD' \
  SEED_PHONE_NUMBER='$SEED_PHONE' \
  npx tsx scripts/seed.ts"

# ── Caddy config ─────────────────────────────────────────────────────────────

echo "Configuring Caddy..."
cat > /etc/caddy/Caddyfile <<CADDYFILE
${DOMAIN} {
    reverse_proxy localhost:3000
}
CADDYFILE

systemctl restart caddy
echo "Caddy: configured for $DOMAIN with automatic TLS"

# ── pm2 processes ────────────────────────────────────────────────────────────

echo "Starting DLR processes..."

# Stop any existing DLR processes
sudo -u "$APP_USER" bash -c "cd $APP_DIR && pm2 delete ecosystem.config.js 2>/dev/null || true"
sudo -u "$APP_USER" bash -c "cd $APP_DIR && pm2 start ecosystem.config.js"
sudo -u "$APP_USER" bash -c "pm2 save"

# Set pm2 to start on boot
env PATH="$PATH:/usr/bin" pm2 startup systemd -u "$APP_USER" --hp "$APP_DIR"

# ── Firewall ─────────────────────────────────────────────────────────────────

if command -v ufw &>/dev/null; then
  echo "Configuring firewall..."
  ufw allow 22/tcp   # SSH
  ufw allow 80/tcp   # HTTP (Caddy redirect)
  ufw allow 443/tcp  # HTTPS (Caddy)
  ufw --force enable
fi

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo "=== DLR is running ==="
echo ""
echo "  App:     https://${DOMAIN}"
echo "  Webhook: https://${DOMAIN}/api/webhooks/telnyx"
echo "  Login:   https://${DOMAIN}/login"
echo ""
echo "  Admin:   ${ADMIN_EMAIL}"
echo ""
echo "  Processes:"
sudo -u "$APP_USER" pm2 list
echo ""
echo "  Logs:    sudo -u $APP_USER pm2 logs"
echo "  Status:  sudo -u $APP_USER pm2 status"
echo "  Restart: sudo -u $APP_USER pm2 restart all"
echo ""
echo "Next steps:"
echo "  1. Verify: curl https://${DOMAIN}/api/webhooks/telnyx -X POST -H 'Content-Type: application/json' -d '{}'"
echo "  2. Set Telnyx webhook URL to: https://${DOMAIN}/api/webhooks/telnyx"
echo "  3. Log in at: https://${DOMAIN}/login"
